[tool.poetry]
name = "Funkwhale"
version = "1.2.1"
description = ""
authors = ["Funkwhale Collective"]
license = "GNU AGPLv3"

[tool.poetry.dependencies]
python = "^3.7"
Django = "==3.2.11"
setuptools = "==57.4.0"
django-environ = "==0.4.5"
Pillow = "==8.3.2"
django-allauth = "==0.42.0"
psycopg2 = "==2.9.3"
pytz = "2021.1"
django-redis = "==5.0.0"
redis = "==3.5.3"
kombu = "==5.1.0"
celery = "==5.1.2"
django-cors-headers = "==3.8.0"
musicbrainzngs = "==0.7.1"
djangorestframework = "==3.12.4"
arrow = "==1.1.1"
persisting-theory = "==0.2.1"
django-versatileimagefield = "==2.2"
django-filter = "==2.4.0"
django-rest-auth = "==0.9.5"
mutagen = "==1.45.1"
PyMemoize = "==1.0.3"
django-dynamic-preferences = "==1.11.0"
python-magic = "==0.4.24"
channels = "==3.0.4"
channels-redis = "==3.3.1"
gunicorn = "==20.1.0"
cryptography = "==36.0.1"
requests-http-signature = {git = "https://github.com/agateblue/requests-http-signature.git", rev = "signature-header-support"}
django-cleanup = "==5.2.0"
requests = "==2.26.0"
pyOpenSSL = "==20.0.1"
pydub = "==0.25.1"
PyLD = "==2.0.3"
aiohttp = "==3.7.4.post0"
django-oauth-toolkit = "==1.5.0"
django-storages = "==1.11.1"
boto3 = "==1.17.112"
unicode-slugify = "==0.1.5"
django-cacheops = "==6.0"
service-identity = "==21.1.0"
click = "==7.1.2"
Markdown = "==3.3.6"
bleach = "==3.3.1"
feedparser = "==6.0.8"
watchdog = "==2.1.6"
asgiref = "3.3.4" #1516
ipython = "==7.27.0"
python-ldap = "==3.3.1"
django-auth-ldap = "==3.0.0"
uvicorn = {version = "==0.14.0", extras = ["standard"]}

[tool.poetry.dev-dependencies]
flake8 = "==3.9.2"
pytest = "==6.2.5"
pytest-cov = "==2.12.1"
pytest-django = "==4.4.0"
pytest-env = "==0.6.2"
pytest-mock = "==3.6.1"
pytest-randomly = "==3.10.3"
pytest-sugar = "==0.9.4"
pytest-asyncio = "==0.15.1"
requests-mock = "==1.9.3"
Faker = "==8.12.3"
coverage = "==5.5"
django-coverage-plugin = "==2.0.2"
factory-boy = "==3.2.1"
django-debug-toolbar = "==3.2.4"
asynctest = "==0.13.0"
aioresponses = "==0.7.3"
prompt-toolkit = "==3.0.26"
black = "==21.12b0"
ipdb = "==0.13.9"
drf-spectacular = "0.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
